name: Quarkus Compatibility Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  test-matrix:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        quarkusVersion:
          - 3.19.1
          - 3.19.2
          - 3.19.3
          - 3.19.4
          - 3.20.0
          - 3.20.1
          - 3.21.0
          - 3.21.1
          - 3.21.2
          - 3.21.3
          - 3.21.4
          - 3.22.1
          - 3.22.2
          - 3.22.3
          - 3.23.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Run Gradle tests with Quarkus ${{ matrix.quarkusVersion }}
        run: |
          ./gradlew clean test \
            -PquarkusPluginVersion=${{ matrix.quarkusVersion }} \
            -PquarkusPlatformVersion=${{ matrix.quarkusVersion }} \
            --rerun-tasks --no-build-cache

